<x-app-layout>
    <x-slot name="header"><div class="page-header"><div><h1 class="page-title">แก้ไขบัญชีผู้ใช้</h1><p class="page-description">ปรับปรุงข้อมูลและสิทธิ์ของ {{ $user->name }}</p></div><a href="{{ route('admin.users.index') }}" class="secondary-action"><i class="fa-solid fa-arrow-left"></i>กลับรายการ</a></div></x-slot>
    <div class="data-page-stack"><div class="data-card p-6"><form method="POST" action="{{ route('admin.users.update', $user) }}" class="grid grid-cols-1 gap-5 md:grid-cols-2" data-confirm-user>@csrf @method('PUT')
        <div><label for="name" class="mb-1 block text-sm font-medium text-slate-700">ชื่อ-นามสกุล</label><input id="name" name="name" value="{{ old('name', $user->name) }}" required class="modal-input">@error('name')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="username" class="mb-1 block text-sm font-medium text-slate-700">ชื่อผู้ใช้</label><input id="username" name="username" value="{{ old('username', $user->username) }}" required class="modal-input">@error('username')<p class="mt-1 text-xs text-rose-600">{{ $message }}</p>@enderror</div>
        <div><label for="phone" class="mb-1 block text-sm font-medium text-slate-700">เบอร์โทรศัพท์</label><input id="phone" name="phone" value="{{ old('phone', $user->phone) }}" class="modal-input"></div>
        <div><label for="department_id" class="mb-1 block text-sm font-medium text-slate-700">แผนก</label><select id="department_id" name="department_id" class="filter-select"><option value="">ไม่ระบุ</option>@foreach ($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id', $user->department_id) == $department->id)>{{ $department->department_name }}</option>@endforeach</select></div>
        <div><label for="role_id" class="mb-1 block text-sm font-medium text-slate-700">บทบาท</label><select id="role_id" name="role_id" required class="filter-select">@foreach ($roles as $role)<option value="{{ $role->id }}" @selected(old('role_id', $user->role_id) == $role->id)>{{ $role->name }}</option>@endforeach</select></div>
        <div><label for="password" class="mb-1 block text-sm font-medium text-slate-700">รหัสผ่านใหม่ <span class="text-xs font-normal text-slate-400">(ไม่เปลี่ยนเว้นว่างไว้)</span></label><input id="password" name="password" type="password" class="modal-input"></div>
        <div><label for="password_confirmation" class="mb-1 block text-sm font-medium text-slate-700">ยืนยันรหัสผ่านใหม่</label><input id="password_confirmation" name="password_confirmation" type="password" class="modal-input"></div>
        <div class="form-actions md:col-span-2"><a href="{{ route('admin.users.index') }}" class="secondary-action">ยกเลิก</a><button type="submit" class="primary-action"><i class="fa-solid fa-save"></i>บันทึกการแก้ไข</button></div>
    </form></div></div>
    <script>document.querySelector('[data-confirm-user]').addEventListener('submit', function (event) { event.preventDefault(); const form = this; Swal.fire({ icon: 'question', title: 'ยืนยันการแก้ไข', text: 'ต้องการบันทึกข้อมูลบัญชีนี้หรือไม่?', showCancelButton: true, confirmButtonText: 'ยืนยัน', cancelButtonText: 'ยกเลิก', confirmButtonColor: '#2563eb', cancelButtonColor: '#94a3b8' }).then(function (result) { if (result.isConfirmed) form.submit(); }); });</script>
</x-app-layout>
